### ISSUE TITLE
Sampling rate mismatch 

### ISSUE THREAD

**Issue by Soumya-dutta** [jrgillick/laughter-detection#16]
Hello @jrgillick ,

Thanks for this work. I have a doubt regarding using this code for laughter detection in datasets which are sampled at 16 kHz. Where all do we need to change the code in that case?

Also, do you expect any drop in performance with this change?

Thanks,
Soumya

**Comment by jrgillick** [comment]
Hi Soumya, if you're using the Colab or the `segment_laughter.py
 script, the code is automatically converting the sample rate to 8000 before running the model. The data loading code is doing the sample rate conversion: https://github.com/jrgillick/laughter-detection/blob/master/utils/data_loaders.py#L183

If you're training your own model, then it's up to you what sample rate you want to use - I was training on the Switchboard dataset, which only comes at 8K, so that's why I use 8K rather than something higher.

**Comment by Soumya-dutta** [comment]
Thanks @jrgillick
