### ISSUE TITLE
Output a time-allign annotation file.

### ISSUE THREAD

**Issue by mwlodarczak** [jrgillick/laughter-detection#5]
At the moment, `segment_laughter.py` cuts out the detected laughter sequences and prints out a list of time locations of these in the original file. It would be useful if in addition it could produce a time-aligned annotation file in some commonly used format.

In phonetics, which is my field, one widely used annotation tool is [Praat](http://www.fon.hum.uva.nl/praat/), which saves its annotations in TextGrid files. I could provide a pull request adding such a functionality.

**Comment by jrgillick** [comment]
Sure, if you think that would be helpful for others, go for it! My only ask would be to try to keep it so that your change doesn't make it harder for me to update the scripts later on.  If you can do it as a function that just takes in my list of time locations as input, and then outputs your file, I think that would work.

**Comment by mwlodarczak** [comment]
Would something like [this](https://github.com/jrgillick/laughter-detection/pull/6) be acceptable? The actual writing to a file is done in `segment_laughter.py`, the only change to `laugh_segmenter.py` is adding an optional argument to `save_cuts` to `segment_laughs`, which defaults to True (hence no change from the original). This is to prevent creation of audio files with individual laughter instances.
